name: NetCup SCP 快照自动管理

on:
  # 手动触发
  workflow_dispatch:
  
  # 定时触发 (每天UTC时间00:00，即北京时间08:00)
  schedule:
    - cron: '0 0 * * *'

jobs:
  snapshot-management:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: 安装 Chrome 浏览器
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: 安装 Python 依赖
      run: |
        python -m pip install --upgrade pip
        pip install DrissionPage
        
    - name: 运行快照管理
      env:
        NC_USERNAME: ${{ secrets.NC_USERNAME }}
        NC_PASSWORD: ${{ secrets.NC_PASSWORD }}
        NC_SERVERS: ${{ secrets.NC_SERVERS }}
        SNAP_COUNT: ${{ vars.SNAP_COUNT || '1' }}
      run: python main.py
      
    - name: 上传运行日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 7
