name: NCSnap

on:
  workflow_dispatch:
  schedule:
    - cron: '44 22 * * *'

jobs:
  NCSnap:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: 环境准备
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        sudo apt-get update && sudo apt-get install -y google-chrome-stable
        pip install DrissionPage
        
    - name: 创建配置文件
      run: |
        echo '${{ secrets.NC_CONFIG }}' > config.json
        
    - name: NCSnap
      run: python main.py
